# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
required = [
  "github.com/tektoncd/plumbing/scripts",
]

[[constraint]]
  name = "github.com/tektoncd/pipeline"
  version = "v0.5.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/tektoncd/plumbing"
  non-go = false

[[constraint]]
  name = "github.com/openshift/client-go"
  version = "3.9.0"
