# Copyright 2020-2024 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --logout-url=--logout-url
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --pipelines-namespace=--pipelines-namespace
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --triggers-namespace=--triggers-namespace
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --read-only=--read-only
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --log-level=--log-level
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --log-format=--log-format
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --namespaces=--tenant-namespaces
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --stream-logs=--stream-logs
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --external-logs=--external-logs
