---
resources:
  - ../../base/rbac-cluster
  - ../openshift-patches/clusterrole.yaml
  - ../openshift-patches/clusterrolebinding.yaml
  - ../openshift-patches/route.yaml
  - ../openshift-patches/internal-dashboard-service.yaml
patches:
  - ../openshift-patches/dashboard-service.yaml
  - ../openshift-patches/serviceaccount.yaml
  - ../openshift-patches/oauth-proxy-in-deployment.yaml
  - ../readonly/readonly-deployment-patch.yaml
  - ../dev/csrf-secure-cookie-patch.yaml
images:
  - name: dashboardImage
    newName: github.com/tektoncd/dashboard/cmd/dashboard
    newTag:
namespace: openshift-pipelines
